Repository EFUB-TEAM4/ewha-weather-frontend, pull requests merged in 2022-07, with the labels that each got.

#11 #5 : [Save] PC, Mobile UI
  package-lock.json
  package.json
  src/AppRouter.js
  src/assets/Arrow/WhiteLeft.svg
  src/assets/Tmp/SaveBear.svg
  src/assets/Tmp/WeatherInfo.svg
  src/assets/index.js
  src/components/CustomCalendar/index.js
  src/components/CustomCalendar/style.js
  src/components/index.js
  src/pages/MyPage/index.js
  src/pages/MyPage/style.js
  src/pages/Save/index.js
  src/pages/Save/style.js
  src/pages/SaveRecord/index.js
  src/pages/SaveRecord/style.js
  src/pages/index.js
Labels: 💚Eunbi💚

#14 #13 [Style] Bear & Weather & Poll
  package-lock.json
  package.json
  src/assets/Bear/MainBear.svg
  src/assets/index.js
  src/components/TempReport/TimeCard/index.jsx
  src/components/TempReport/TimeCard/style.js
  src/components/TempReport/index.jsx
  src/components/TempReport/style.js
  src/components/WeatherReport/index.jsx
  src/components/WeatherReport/style.js
  src/components/index.js
  src/pages/Main/Vote/index.jsx
  src/pages/Main/Vote/style.js
  src/pages/Main/Weather/index.jsx
  src/pages/Main/Weather/style.js
  src/pages/Main/index.js
  src/pages/Main/index.jsx
  src/pages/Main/style.js
  src/pages/MyPage/index.jsx
  src/styles/styleOptions/fonts.js
Labels: enhancement, 💙𝗔𝘆𝗲𝗼𝗻💙

#19 #7 : [MyPage] Modal and Page UI
  package-lock.json
  src/components/EditModal/index.js
  src/components/EditModal/style.js
  src/components/index.js
  src/pages/SaveRecord/index.js
  src/pages/SaveRecord/style.js
Labels: 💛SoHyun💛

#21 #17 [Vote] PC, Mobile UI
  src/AppRouter.js
  src/pages/Save/SaveComplete/index.js
  src/pages/Save/SaveComplete/style.js
  src/pages/Vote/VoteComplete/index.js
  src/pages/Vote/VoteComplete/style.js
  src/pages/Vote/index.js
  src/pages/Vote/style.js
  src/pages/index.js
Labels: 💚Eunbi💚

#22 #6 : [Save] Button active
  src/pages/Save/SaveComplete/index.js
  src/pages/Save/index.js
  src/pages/Save/style.js
Labels: 💚Eunbi💚

#23 #13 [Main] Share Modal & Bear Avater Options
  package-lock.json
  package.json
  src/apis/Imgur/uploadImgur.api.js
  src/apis/index.js
  src/assets/Bear/Bear.png
  src/assets/Bear/CancelLogo.svg
  src/assets/Bear/OverBear.svg
  src/assets/Bear/School.png
  src/assets/Bear/SkyDark.png
  src/assets/Bear/Snow.png
  src/assets/Bear/options/CloseModal.svg
  src/assets/Bear/options/LocalBtn.svg
  src/assets/Bear/options/MoreBtn.svg
  src/assets/Bear/options/RecBtn.svg
  src/assets/Bear/options/ShareBtn.svg
  src/assets/Share/CloseShare.svg
  src/assets/Share/Insta.svg
  src/assets/Share/Kakao.svg
  src/assets/Share/Link.svg
  src/assets/Share/Local.svg
  src/assets/Share/Twitter.svg
  src/assets/index.js
  src/components/Common/BearAvater/index.jsx
  src/components/Common/BearAvater/style.js
  src/components/Icon/Google.svg
  src/components/PollCard/Mobile/bar/index.jsx
  src/components/ShareModal/index.jsx
  src/components/ShareModal/style.js
  src/components/index.js
  src/hooks/useWindowWidth.js
  src/pages/Login/index.js
  src/pages/Main/BearOptions/Cloth/index.jsx
  src/pages/Main/BearOptions/Cloth/style.js
  src/pages/Main/BearOptions/Share/index.jsx
  src/pages/Main/BearOptions/Share/style.js
  src/pages/Main/BearOptions/index.jsx
  src/pages/Main/BearOptions/style.js
  src/pages/Main/Weather/WeatherReport/style.js
  src/pages/Main/Weather/index.jsx
  src/pages/Main/Weather/style.js
  src/pages/Main/style.js
  src/styles/styleOptions/colors.js
  src/utils/PngBear.js
  src/utils/index.js
  src/utils/isEwha1.js
Labels: enhancement, 💙𝗔𝘆𝗲𝗼𝗻💙

#25 #17 [Vote] Button & VoteComplete Params
  src/AppRouter.js
  src/pages/Vote/VoteComplete/index.js
  src/pages/Vote/VoteComplete/style.js
  src/pages/Vote/index.js
  src/pages/Vote/style.js
Labels: 💚Eunbi💚

#24 #4 [MyPage] Nickname Input & Calendar
  src/assets/Pencil/WhiteNormalPencil.svg
  src/assets/Pencil/WhiteOutlinePencil.svg
  src/assets/index.js
  src/components/CustomCalendar/index.js
  src/pages/MyPage/index.jsx
  src/pages/MyPage/style.js
Labels: 💛SoHyun💛

#26 #4 [Save] axios test
  src/pages/Save/index.js
Labels: 💛SoHyun💛

#28 #17 [Vote] place basic parameters
  src/pages/Vote/index.js
Labels: 💚Eunbi💚
