Repository EFUB-TEAM4/ewha-weather-frontend, pull requests merged in 2022-08, with the labels that each got.

#40 #4 [Feat] Calendar & Save & SaveRecord Axios
  src/AppRouter.js
  src/apis/Calendar.apis.js
  src/components/Common/HeaderIcon/index.js
  src/components/CustomCalendar/index.js
  src/constants/bearImg.js
  src/hooks/index.js
  src/hooks/logout.js
  src/pages/MyPage/index.jsx
  src/pages/MyPage/style.js
  src/pages/Save/SaveComplete/index.js
  src/pages/Save/SaveComplete/style.js
  src/pages/Save/index.js
  src/pages/Save/style.js
  src/pages/SaveRecord/index.js
  src/pages/SaveRecord/style.js
Labels: 💛SoHyun💛

#42 #17 [Vote] Vote post Axios
  src/apis/Vote.apis.js
  src/pages/Vote/index.js
Labels: 💚Eunbi💚

#43 #[Style & Feat] 공유 기능 & 투표 반응형 CSS
  .github/workflows/main.yaml
  src/components/Common/BearAvater/style.js
  src/components/PollCard/Mobile/bar/index.jsx
  src/components/PollCard/Mobile/bar/style.js
  src/components/PollCard/Mobile/index.jsx
  src/components/PollCard/PC/bar/index.jsx
  src/components/PollCard/PC/bar/style.js
  src/components/PollCard/PC/index.jsx
  src/pages/Main/BearOptions/Cloth/index.jsx
  src/pages/Main/BearOptions/Share/index.jsx
  src/pages/Main/BearOptions/Share/style.js
  src/pages/Main/BearOptions/style.js
  src/utils/PngBear.js
  src/utils/copyUrl.js
  src/utils/getUrl.js
  src/utils/index.js
  src/utils/shareTwit.js
Labels: 💙𝗔𝘆𝗲𝗼𝗻💙

#45 [Feat] Kakao Share function
  src/pages/Main/BearOptions/Share/index.jsx
  src/pages/MyPage/index.jsx
  src/utils/index.js
  src/utils/shareKakao.js
Labels: 💛SoHyun💛

#46 [Vote] fix vote page UI
  src/pages/Save/style.js
  src/pages/Vote/style.js
Labels: 💚Eunbi💚

#78 #4 [Fixed] Vote Mobile Header Style
  src/pages/Vote/index.js
  src/pages/Vote/style.js
Labels: 💛SoHyun💛
